/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andrewpetrowski_diploma_raspberry_Sensors_BMP180 */

#ifndef _Included_com_andrewpetrowski_diploma_raspberry_Sensors_BMP180
#define _Included_com_andrewpetrowski_diploma_raspberry_Sensors_BMP180
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andrewpetrowski_diploma_raspberry_Sensors_BMP180
 * Method:    GetDataEx
 * Signature: ()Lcom/andrewpetrowski/diploma/bridgelib/Models/Bmp180_Data;
 */
JNIEXPORT jobject JNICALL Java_com_andrewpetrowski_diploma_raspberry_Sensors_BMP180_GetDataEx
  (JNIEnv *, jobject);

/*
 * Class:     com_andrewpetrowski_diploma_raspberry_Sensors_BMP180
 * Method:    GetData
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_andrewpetrowski_diploma_raspberry_Sensors_BMP180_GetData
  (JNIEnv *, jobject);

/*
 * Class:     com_andrewpetrowski_diploma_raspberry_Sensors_BMP180
 * Method:    Testing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_andrewpetrowski_diploma_raspberry_Sensors_BMP180_Testing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
