/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_angpysha_diploma_raspberry_Sensors_BMP180 */

#ifndef _Included_io_github_angpysha_diploma_raspberry_Sensors_BMP180
#define _Included_io_github_angpysha_diploma_raspberry_Sensors_BMP180
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_angpysha_diploma_raspberry_Sensors_BMP180
 * Method:    GetDataEx
 * Signature: ()Lio/github/angpysha/diploma_bridge/Models/Bmp180_Data;
 */
JNIEXPORT jobject JNICALL Java_io_github_angpysha_diploma_1raspberry_Sensors_BMP180_GetDataEx
  (JNIEnv *, jobject);

/*
 * Class:     io_github_angpysha_diploma_raspberry_Sensors_BMP180
 * Method:    GetData
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_github_angpysha_diploma_1raspberry_Sensors_BMP180_GetData
  (JNIEnv *, jobject);

/*
 * Class:     io_github_angpysha_diploma_raspberry_Sensors_BMP180
 * Method:    Testing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_angpysha_diploma_1raspberry_Sensors_BMP180_Testing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
