/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_angpysha_diploma_raspberry_Sensors_DHT11 */

#ifndef _Included_io_github_angpysha_diploma_raspberry_Sensors_DHT11
#define _Included_io_github_angpysha_diploma_raspberry_Sensors_DHT11
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_angpysha_diploma_raspberry_Sensors_DHT11_MAXTIMINGS
#define io_github_angpysha_diploma_raspberry_Sensors_DHT11_MAXTIMINGS 85L
/*
 * Class:     io_github_angpysha_diploma_raspberry_Sensors_DHT11
 * Method:    GetDhtData
 * Signature: (I)Lio/github/angpysha/diploma_bridge/Models/DHT11_Data;
 */
JNIEXPORT jobject JNICALL Java_io_github_angpysha_diploma_1raspberry_Sensors_DHT11_GetDhtData
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_angpysha_diploma_raspberry_Sensors_DHT11
 * Method:    readData
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_github_angpysha_diploma_1raspberry_Sensors_DHT11_readData
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
